import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, Navigate, useSearchParams } from 'react-router-dom';
import { aiUatApi, ssoLoginUrl } from '../api/aiUat';
import { productRegistryApi } from '../api/productRegistry';
import CredentialProfilesSection from '../components/CredentialProfilesSection';

export default function AccountPage(){
  const qc=useQueryClient(); const [params]=useSearchParams();
  const session=useQuery({queryKey:['current-user'],queryFn:aiUatApi.currentUser,retry:false});
  const sso=useQuery({queryKey:['sso-providers'],queryFn:aiUatApi.ssoProviders,retry:false});
  const initialMode=params.get('mode')==='register'?'register':'login'; const [mode,setMode]=useState<'login'|'register'>(initialMode);
  const [companyName,setCompanyName]=useState(''); const [slug,setSlug]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
  const [memberEmail,setMemberEmail]=useState(''); const [memberPassword,setMemberPassword]=useState(''); const [memberRole,setMemberRole]=useState<'COMPANY_ADMIN'|'QA_MANAGER'|'TESTER'|'VIEWER'>('TESTER');
  const [productName,setProductName]=useState(''); const [baseUrl,setBaseUrl]=useState(''); const [environment,setEnvironment]=useState('UAT'); const [authType,setAuthType]=useState('NONE');
  const isPlatform=session.data?.role==='PLATFORM_ADMIN'||session.data?.role==='SUPER_ADMIN';
  const isCompanyAdmin=session.data?.role==='COMPANY_ADMIN';
  const googleEnabled=sso.data?.providers.includes('google')??false;
  const githubEnabled=sso.data?.providers.includes('github')??false;
  const anySsoEnabled=googleEnabled||githubEnabled;

  const login=useMutation({mutationFn:()=>aiUatApi.login(email,password),onSuccess:async()=>{setPassword('');await qc.invalidateQueries({queryKey:['current-user']})}});
  const register=useMutation({mutationFn:async()=>{await aiUatApi.registerCompany({companyName,slug,adminEmail:email,password});return aiUatApi.login(email,password)},onSuccess:async()=>{setPassword('');await qc.invalidateQueries({queryKey:['current-user']})}});
  const users=useQuery({queryKey:['company-users'],queryFn:aiUatApi.companyUsers,enabled:isCompanyAdmin,retry:false});
  const createUser=useMutation({mutationFn:()=>aiUatApi.createCompanyUser({email:memberEmail,password:memberPassword,role:memberRole}),onSuccess:async()=>{setMemberEmail('');setMemberPassword('');await qc.invalidateQueries({queryKey:['company-users']})}});
  const deactivate=useMutation({mutationFn:(id:string)=>aiUatApi.deactivateCompanyUser(id),onSuccess:()=>qc.invalidateQueries({queryKey:['company-users']})});
  const canManageProducts=isCompanyAdmin||session.data?.role==='QA_MANAGER';
  const products=useQuery({queryKey:['company-products'],queryFn:()=>productRegistryApi.list(false),enabled:!!session.data&&!isPlatform,retry:false});
  const createProduct=useMutation({mutationFn:()=>productRegistryApi.create({name:productName,baseUrl,environment,authType}),onSuccess:async()=>{setProductName('');setBaseUrl('');setEnvironment('UAT');setAuthType('NONE');await qc.invalidateQueries({queryKey:['company-products']})}});
  const setProductActive=useMutation({mutationFn:({id,value}:{id:string;value:boolean})=>productRegistryApi.setActive(id,value),onSuccess:()=>qc.invalidateQueries({queryKey:['company-products']})});
  const submit=(e:FormEvent)=>{e.preventDefault();mode==='login'?login.mutate():register.mutate()};
  const submitMember=(e:FormEvent)=>{e.preventDefault();createUser.mutate()};
  const submitProduct=(e:FormEvent)=>{e.preventDefault();createProduct.mutate()};
  const error=login.error||register.error;

  if(session.data&&isPlatform)return <Navigate to="/platform" replace/>;

  if(session.data){return <main className="page compact-page">
    <div className="page-heading compact-heading"><div><div className="eyebrow">COMPANY SETUP</div><h1>Workspace setup</h1><p className="lead">Manage only the items your team needs to run UAT. Account identity and session details are available from the top-right account tray.</p></div><Link className="primary-btn" to="/mission">Start UAT</Link></div>

    {isCompanyAdmin&&<section className="panel"><div className="section-heading"><div><h2>Team</h2><p className="muted">Add or deactivate company users.</p></div><span>{users.data?.filter(u=>u.active).length??0} active</span></div><form onSubmit={submitMember}><div className="form-grid"><label className="field"><span>Email</span><input type="email" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)} required placeholder="qa@company.com"/></label><label className="field"><span>Temporary password</span><input type="password" minLength={12} value={memberPassword} onChange={e=>setMemberPassword(e.target.value)} required/></label><label className="field"><span>Role</span><select value={memberRole} onChange={e=>setMemberRole(e.target.value as typeof memberRole)}><option value="COMPANY_ADMIN">Company Admin</option><option value="QA_MANAGER">QA Manager</option><option value="TESTER">Tester</option><option value="VIEWER">Viewer</option></select></label></div><button className="primary-btn" disabled={createUser.isPending}>{createUser.isPending?'Adding…':'Add team member'}</button>{createUser.isError&&<p className="error-text">{createUser.error.message}</p>}</form><div className="stack-list">{users.data?.map(user=><div className="list-card" key={user.id}><div><strong>{user.email}</strong><small>{user.role}</small></div><div className="button-row"><span className={`status ${user.active?'completed':'failed'}`}>{user.active?'ACTIVE':'INACTIVE'}</span>{user.active&&user.id!==session.data.id&&<button className="secondary-btn" onClick={()=>deactivate.mutate(user.id)} disabled={deactivate.isPending}>Deactivate</button>}</div></div>)}</div></section>}

    <section className="panel"><div className="section-heading"><div><h2>Products</h2><p className="muted">Register approved UAT, QA or DEV targets.</p></div><span>{products.data?.filter(p=>p.active).length??0} active</span></div>{products.isError&&<p className="error-text">{products.error.message}</p>}{canManageProducts&&<form onSubmit={submitProduct}><div className="form-grid"><label className="field"><span>Product name</span><input value={productName} onChange={e=>setProductName(e.target.value)} required placeholder="Customer Portal"/></label><label className="field"><span>Target URL</span><input type="url" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} required placeholder="https://uat.example.com"/></label><label className="field"><span>Environment</span><select value={environment} onChange={e=>setEnvironment(e.target.value)}><option>UAT</option><option>QA</option><option>DEV</option></select></label><label className="field"><span>Authentication</span><select value={authType} onChange={e=>setAuthType(e.target.value)}><option>NONE</option><option>USERNAME_PASSWORD</option><option>API_TOKEN</option><option>OIDC</option></select></label></div><button className="primary-btn" disabled={createProduct.isPending}>{createProduct.isPending?'Registering…':'Register product'}</button>{createProduct.isError&&<p className="error-text">{createProduct.error.message}</p>}</form>}<div className="stack-list">{products.data?.map(product=><div className="list-card" key={product.id}><div><strong>{product.name}</strong><small>{product.environment} • {product.baseUrl} • {product.authType}</small></div><div className="button-row"><span className={`status ${product.active?'completed':'failed'}`}>{product.active?'ACTIVE':'INACTIVE'}</span>{canManageProducts&&<button className="secondary-btn" onClick={()=>setProductActive.mutate({id:product.id,value:!product.active})} disabled={setProductActive.isPending}>{product.active?'Deactivate':'Activate'}</button>}</div></div>)}</div></section>

    <section className="panel"><div className="section-heading"><div><h2>Credentials</h2><p className="muted">Attach runtime credentials only for products that require authentication.</p></div></div><CredentialProfilesSection products={products.data||[]} canManage={!!canManageProducts}/></section>
  </main>}

  return <main className="page auth-page"><section className="hero-grid simple-hero"><div><div className="eyebrow">AI UAT ENGINEER</div><h1>{mode==='login'?'Sign in':'Create your company'}</h1><p className="lead">{mode==='login'?'Sign in once, then continue directly with your company UAT workspace.':'Create the workspace. Your first account becomes Company Admin.'}</p></div><section className="panel"><div className="button-row"><button className={mode==='login'?'primary-btn':'secondary-btn'} type="button" onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'primary-btn':'secondary-btn'} type="button" onClick={()=>setMode('register')}>Register</button></div><form onSubmit={submit}>{mode==='register'&&<><label className="field"><span>Company name</span><input value={companyName} onChange={e=>setCompanyName(e.target.value)} required placeholder="Acme Technologies"/></label><label className="field"><span>Company slug <small>(optional)</small></span><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="acme-technologies"/></label></>}<label className="field"><span>Work email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" placeholder="you@company.com"/></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={12} autoComplete={mode==='login'?'current-password':'new-password'}/></label><button className="primary-btn" disabled={login.isPending||register.isPending}>{login.isPending||register.isPending?'Please wait…':mode==='login'?'Sign in':'Create workspace'}</button>{error&&<p className="error-text">{error.message}</p>}</form>{mode==='login'&&<div className="stack-list">{anySsoEnabled&&<div className="button-row">{googleEnabled&&<a className="secondary-btn" href={ssoLoginUrl('google')}>Google</a>}{githubEnabled&&<a className="secondary-btn" href={ssoLoginUrl('github')}>GitHub</a>}</div>}{!sso.isLoading&&!anySsoEnabled&&<p className="muted">SSO is not configured. Use email and password.</p>}</div>}</section></section></main>
}
