import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { aiUatApi } from '../api/aiUat';
import { productRegistryApi } from '../api/productRegistry';

export default function AccountPage(){
  const qc=useQueryClient();
  const session=useQuery({queryKey:['current-user'],queryFn:aiUatApi.currentUser,retry:false});
  const [mode,setMode]=useState<'login'|'register'>('login');
  const [companyName,setCompanyName]=useState(''); const [slug,setSlug]=useState('');
  const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
  const [memberEmail,setMemberEmail]=useState(''); const [memberPassword,setMemberPassword]=useState(''); const [memberRole,setMemberRole]=useState<'QA_MANAGER'|'TESTER'|'VIEWER'>('TESTER');
  const [productName,setProductName]=useState(''); const [baseUrl,setBaseUrl]=useState(''); const [environment,setEnvironment]=useState('UAT'); const [authType,setAuthType]=useState('NONE');

  const login=useMutation({mutationFn:()=>aiUatApi.login(email,password),onSuccess:async()=>{setPassword('');await qc.invalidateQueries({queryKey:['current-user']})}});
  const register=useMutation({mutationFn:async()=>{await aiUatApi.registerCompany({companyName,slug,adminEmail:email,password});return aiUatApi.login(email,password)},onSuccess:async()=>{setPassword('');await qc.invalidateQueries({queryKey:['current-user']})}});
  const logout=useMutation({mutationFn:aiUatApi.logout,onSuccess:async()=>{await qc.invalidateQueries({queryKey:['current-user']});qc.removeQueries({queryKey:['company-users']});qc.removeQueries({queryKey:['company-products']})}});
  const users=useQuery({queryKey:['company-users'],queryFn:aiUatApi.companyUsers,enabled:session.data?.role==='COMPANY_ADMIN',retry:false});
  const createUser=useMutation({mutationFn:()=>aiUatApi.createCompanyUser({email:memberEmail,password:memberPassword,role:memberRole}),onSuccess:async()=>{setMemberEmail('');setMemberPassword('');await qc.invalidateQueries({queryKey:['company-users']})}});
  const deactivate=useMutation({mutationFn:(id:string)=>aiUatApi.deactivateCompanyUser(id),onSuccess:()=>qc.invalidateQueries({queryKey:['company-users']})});
  const canManageProducts=session.data?.role==='COMPANY_ADMIN'||session.data?.role==='QA_MANAGER';
  const products=useQuery({queryKey:['company-products'],queryFn:()=>productRegistryApi.list(false),enabled:!!session.data,retry:false});
  const createProduct=useMutation({mutationFn:()=>productRegistryApi.create({name:productName,baseUrl,environment,authType}),onSuccess:async()=>{setProductName('');setBaseUrl('');setEnvironment('UAT');setAuthType('NONE');await qc.invalidateQueries({queryKey:['company-products']})}});
  const setProductActive=useMutation({mutationFn:({id,value}:{id:string;value:boolean})=>productRegistryApi.setActive(id,value),onSuccess:()=>qc.invalidateQueries({queryKey:['company-products']})});
  const submit=(e:FormEvent)=>{e.preventDefault();mode==='login'?login.mutate():register.mutate()};
  const submitMember=(e:FormEvent)=>{e.preventDefault();createUser.mutate()};
  const submitProduct=(e:FormEvent)=>{e.preventDefault();createProduct.mutate()};
  const error=login.error||register.error;

  if(session.data){return <main className="page"><div className="eyebrow">4.0 • M16 COMPANY WORKSPACE</div><h1>Your account</h1><p className="lead">Manage your company users and registered UAT product environments.</p><section className="panel"><div className="metric-grid four compact"><article><strong>{session.data.email}</strong><span>User</span></article><article><strong>{session.data.role}</strong><span>Role</span></article><article><strong>{session.data.companyId.slice(0,8)}…</strong><span>Company</span></article><article><strong>Active</strong><span>Session</span></article></div><div className="form-actions"><button className="secondary-btn" onClick={()=>logout.mutate()} disabled={logout.isPending}>{logout.isPending?'Signing out…':'Sign out'}</button></div></section>

    {session.data.role==='COMPANY_ADMIN'&&<><section className="panel"><div className="section-heading"><div><div className="eyebrow">COMPANY USERS</div><h2>Add a team member</h2></div></div><p className="muted">Users created here are automatically restricted to this company workspace.</p><form onSubmit={submitMember}><div className="form-grid"><label className="field"><span>Email</span><input type="email" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)} required/></label><label className="field"><span>Temporary password</span><input type="password" minLength={12} value={memberPassword} onChange={e=>setMemberPassword(e.target.value)} required/><small>Minimum 12 characters.</small></label><label className="field"><span>Role</span><select value={memberRole} onChange={e=>setMemberRole(e.target.value as 'QA_MANAGER'|'TESTER'|'VIEWER')}><option value="QA_MANAGER">QA Manager</option><option value="TESTER">Tester</option><option value="VIEWER">Viewer</option></select></label></div><button className="primary-btn" disabled={createUser.isPending}>{createUser.isPending?'Adding user…':'Add user'}</button>{createUser.isError&&<p className="error-text">{createUser.error.message}</p>}</form></section>

    <section className="panel"><div className="section-heading"><div><div className="eyebrow">TEAM</div><h2>Company users</h2></div></div>{users.isLoading&&<p className="muted">Loading users…</p>}{users.isError&&<p className="error-text">Unable to load company users.</p>}<div className="stack-list">{users.data?.map(user=><div className="list-card" key={user.id}><div><strong>{user.email}</strong><small>{user.role} • {user.active?'Active':'Inactive'}</small></div><div className="button-row"><span className={`status ${user.active?'completed':'failed'}`}>{user.active?'ACTIVE':'INACTIVE'}</span>{user.active&&user.id!==session.data.id&&<button className="secondary-btn" onClick={()=>deactivate.mutate(user.id)} disabled={deactivate.isPending}>Deactivate</button>}</div></div>)}</div>{deactivate.isError&&<p className="error-text">{deactivate.error.message}</p>}</section></>}

    {canManageProducts&&<section className="panel"><div className="section-heading"><div><div className="eyebrow">M16 PRODUCT REGISTRY</div><h2>Register a product environment</h2></div></div><p className="muted">The company is taken from your signed-in session. Users do not enter a tenant ID.</p><form onSubmit={submitProduct}><div className="form-grid"><label className="field"><span>Product name</span><input value={productName} onChange={e=>setProductName(e.target.value)} required placeholder="Customer Portal"/></label><label className="field"><span>UAT URL</span><input type="url" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} required placeholder="https://uat.example.com"/></label><label className="field"><span>Environment</span><select value={environment} onChange={e=>setEnvironment(e.target.value)}><option>UAT</option><option>QA</option><option>DEV</option></select></label><label className="field"><span>Authentication</span><select value={authType} onChange={e=>setAuthType(e.target.value)}><option>NONE</option><option>USERNAME_PASSWORD</option><option>API_TOKEN</option><option>OIDC</option></select></label></div><button className="primary-btn" disabled={createProduct.isPending}>{createProduct.isPending?'Registering…':'Register product environment'}</button>{createProduct.isError&&<p className="error-text">{createProduct.error.message}</p>}</form></section>}

    <section className="panel"><div className="section-heading"><div><div className="eyebrow">REGISTERED TARGETS</div><h2>Company product environments</h2></div></div>{products.isLoading&&<p className="muted">Loading products…</p>}{products.isError&&<p className="error-text">Unable to load registered products.</p>}<div className="stack-list">{products.data?.map(product=><div className="list-card" key={product.id}><div><strong>{product.name}</strong><small>{product.environment} • {product.baseUrl} • {product.authType}</small></div><div className="button-row"><span className={`status ${product.active?'completed':'failed'}`}>{product.active?'ACTIVE':'INACTIVE'}</span>{canManageProducts&&<button className="secondary-btn" onClick={()=>setProductActive.mutate({id:product.id,value:!product.active})} disabled={setProductActive.isPending}>{product.active?'Deactivate':'Activate'}</button>}</div></div>)}</div>{setProductActive.isError&&<p className="error-text">{setProductActive.error.message}</p>}</section>
  </main>}

  return <main className="page"><div className="eyebrow">4.0 • M14 AUTHENTICATION</div><h1>{mode==='login'?'Sign in':'Register your company'}</h1><p className="lead">{mode==='login'?'Use your company account to access AI UAT Engineer.':'Create a company workspace and its first Company Admin account.'}</p><section className="panel"><div className="button-row"><button className={mode==='login'?'primary-btn':'secondary-btn'} type="button" onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'primary-btn':'secondary-btn'} type="button" onClick={()=>setMode('register')}>Register company</button></div><form onSubmit={submit}>{mode==='register'&&<div className="form-grid"><label className="field"><span>Company name</span><input value={companyName} onChange={e=>setCompanyName(e.target.value)} required placeholder="Acme Technologies"/></label><label className="field"><span>Company slug</span><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="acme-technologies"/><small>Optional. Generated from company name if left blank.</small></label></div>}<div className="form-grid"><label className="field"><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={12} autoComplete={mode==='login'?'current-password':'new-password'}/><small>Minimum 12 characters.</small></label></div><div className="form-actions"><button className="primary-btn" disabled={login.isPending||register.isPending}>{login.isPending||register.isPending?'Please wait…':mode==='login'?'Sign in':'Create company & sign in'}</button></div>{error&&<p className="error-text">{error.message}</p>}</form></section><section className="panel"><div className="eyebrow">WHAT COMES NEXT</div><div className="example-flow"><span>Company</span><i>→</i><span>Company Admin</span><i>→</i><span>Users</span><i>→</i><span>Products</span><i>→</i><strong>Autonomous UAT</strong></div></section></main>
}
