import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { aiUatApi, ssoLoginUrl } from '../api/aiUat';
import { productRegistryApi } from '../api/productRegistry';
import CredentialProfilesSection from '../components/CredentialProfilesSection';

export default function AccountPage(){
  const qc=useQueryClient(); const [params]=useSearchParams();
  const session=useQuery({queryKey:['current-user'],queryFn:aiUatApi.currentUser,retry:false});
  const sso=useQuery({queryKey:['sso-providers'],queryFn:aiUatApi.ssoProviders,retry:false});
  const initialMode=params.get('mode')==='register'?'register':'login'; const [mode,setMode]=useState<'login'|'register'>(initialMode);
  const [companyName,setCompanyName]=useState(''); const [slug,setSlug]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
  const [memberEmail,setMemberEmail]=useState(''); const [memberPassword,setMemberPassword]=useState(''); const [memberRole,setMemberRole]=useState<'QA_MANAGER'|'TESTER'|'VIEWER'>('TESTER');
  const [productName,setProductName]=useState(''); const [baseUrl,setBaseUrl]=useState(''); const [environment,setEnvironment]=useState('UAT'); const [authType,setAuthType]=useState('NONE');
  const isPlatform=session.data?.role==='PLATFORM_ADMIN';
  const googleEnabled=sso.data?.providers.includes('google')??false;
  const githubEnabled=sso.data?.providers.includes('github')??false;

  const login=useMutation({mutationFn:()=>aiUatApi.login(email,password),onSuccess:async()=>{setPassword('');await qc.invalidateQueries({queryKey:['current-user']})}});
  const register=useMutation({mutationFn:async()=>{await aiUatApi.registerCompany({companyName,slug,adminEmail:email,password});return aiUatApi.login(email,password)},onSuccess:async()=>{setPassword('');await qc.invalidateQueries({queryKey:['current-user']})}});
  const logout=useMutation({mutationFn:aiUatApi.logout,onSuccess:()=>{qc.clear();window.location.replace('/')}});
  const users=useQuery({queryKey:['company-users'],queryFn:aiUatApi.companyUsers,enabled:session.data?.role==='COMPANY_ADMIN',retry:false});
  const createUser=useMutation({mutationFn:()=>aiUatApi.createCompanyUser({email:memberEmail,password:memberPassword,role:memberRole}),onSuccess:async()=>{setMemberEmail('');setMemberPassword('');await qc.invalidateQueries({queryKey:['company-users']})}});
  const deactivate=useMutation({mutationFn:(id:string)=>aiUatApi.deactivateCompanyUser(id),onSuccess:()=>qc.invalidateQueries({queryKey:['company-users']})});
  const canManageProducts=session.data?.role==='COMPANY_ADMIN'||session.data?.role==='QA_MANAGER';
  const products=useQuery({queryKey:['company-products'],queryFn:()=>productRegistryApi.list(false),enabled:!!session.data&&!isPlatform,retry:false});
  const createProduct=useMutation({mutationFn:()=>productRegistryApi.create({name:productName,baseUrl,environment,authType}),onSuccess:async()=>{setProductName('');setBaseUrl('');setEnvironment('UAT');setAuthType('NONE');await qc.invalidateQueries({queryKey:['company-products']})}});
  const setProductActive=useMutation({mutationFn:({id,value}:{id:string;value:boolean})=>productRegistryApi.setActive(id,value),onSuccess:()=>qc.invalidateQueries({queryKey:['company-products']})});
  const submit=(e:FormEvent)=>{e.preventDefault();mode==='login'?login.mutate():register.mutate()}; const submitMember=(e:FormEvent)=>{e.preventDefault();createUser.mutate()}; const submitProduct=(e:FormEvent)=>{e.preventDefault();createProduct.mutate()};
  const error=login.error||register.error;

  if(session.data&&isPlatform){return <main className="page"><div className="eyebrow">4.0 • M20 PLATFORM OWNER</div><h1>Platform owner account</h1><p className="lead">You are signed in with read-only cross-company oversight. Customer credentials and password data are never exposed.</p><section className="panel"><div className="summary-strip"><article><strong>{session.data.email}</strong><span>Platform owner</span></article><article><strong>PLATFORM_ADMIN</strong><span>Role</span></article><article><strong>Read only</strong><span>Tenant oversight</span></article><article><strong>Active</strong><span>Session</span></article></div><div className="form-actions"><Link className="primary-btn" to="/platform">Open Platform Console</Link><button className="secondary-btn" onClick={()=>logout.mutate()} disabled={logout.isPending}>{logout.isPending?'Signing out…':'Sign out'}</button></div></section><section className="panel"><div className="eyebrow">OVERSIGHT BOUNDARY</div><div className="example-flow"><span>Companies</span><i>→</i><span>Products</span><i>→</i><span>Users</span><i>→</i><strong>Read-only platform reporting</strong></div></section></main>}

  if(session.data){return <main className="page"><div className="eyebrow">4.0 • COMPANY WORKSPACE</div><h1>Your account</h1><p className="lead">Manage your company users, registered UAT product environments and safe credential references.</p><section className="panel"><div className="metric-grid four compact"><article><strong>{session.data.email}</strong><span>User</span></article><article><strong>{session.data.role}</strong><span>Role</span></article><article><strong>{session.data.companyId.slice(0,8)}…</strong><span>Company</span></article><article><strong>Active</strong><span>Session</span></article></div><div className="form-actions"><button className="secondary-btn" onClick={()=>logout.mutate()} disabled={logout.isPending}>{logout.isPending?'Signing out…':'Sign out'}</button></div></section>
    {session.data.role==='COMPANY_ADMIN'&&<><section className="panel"><div className="section-heading"><div><div className="eyebrow">COMPANY USERS</div><h2>Add a team member</h2></div></div><p className="muted">Users created here are automatically restricted to this company workspace.</p><form onSubmit={submitMember}><div className="form-grid"><label className="field"><span>Email</span><input type="email" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)} required/></label><label className="field"><span>Temporary password</span><input type="password" minLength={12} value={memberPassword} onChange={e=>setMemberPassword(e.target.value)} required/><small>Minimum 12 characters.</small></label><label className="field"><span>Role</span><select value={memberRole} onChange={e=>setMemberRole(e.target.value as 'QA_MANAGER'|'TESTER'|'VIEWER')}><option value="QA_MANAGER">QA Manager</option><option value="TESTER">Tester</option><option value="VIEWER">Viewer</option></select></label></div><button className="primary-btn" disabled={createUser.isPending}>{createUser.isPending?'Adding user…':'Add user'}</button>{createUser.isError&&<p className="error-text">{createUser.error.message}</p>}</form></section><section className="panel"><div className="section-heading"><div><div className="eyebrow">TEAM</div><h2>Company users</h2></div></div>{users.isLoading&&<p className="muted">Loading users…</p>}{users.isError&&<p className="error-text">Unable to load company users.</p>}<div className="stack-list">{users.data?.map(user=><div className="list-card" key={user.id}><div><strong>{user.email}</strong><small>{user.role} • {user.active?'Active':'Inactive'}</small></div><div className="button-row"><span className={`status ${user.active?'completed':'failed'}`}>{user.active?'ACTIVE':'INACTIVE'}</span>{user.active&&user.id!==session.data.id&&<button className="secondary-btn" onClick={()=>deactivate.mutate(user.id)} disabled={deactivate.isPending}>Deactivate</button>}</div></div>)}</div>{deactivate.isError&&<p className="error-text">{deactivate.error.message}</p>}</section></>}
    {canManageProducts&&<section className="panel"><div className="section-heading"><div><div className="eyebrow">PRODUCT REGISTRY</div><h2>Register a product environment</h2></div></div><p className="muted">The company is taken from your signed-in session. Users do not enter a tenant ID.</p><form onSubmit={submitProduct}><div className="form-grid"><label className="field"><span>Product name</span><input value={productName} onChange={e=>setProductName(e.target.value)} required placeholder="Customer Portal"/></label><label className="field"><span>UAT URL</span><input type="url" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} required placeholder="https://uat.example.com"/></label><label className="field"><span>Environment</span><select value={environment} onChange={e=>setEnvironment(e.target.value)}><option>UAT</option><option>QA</option><option>DEV</option></select></label><label className="field"><span>Authentication</span><select value={authType} onChange={e=>setAuthType(e.target.value)}><option>NONE</option><option>USERNAME_PASSWORD</option><option>API_TOKEN</option><option>OIDC</option></select></label></div><button className="primary-btn" disabled={createProduct.isPending}>{createProduct.isPending?'Registering…':'Register product environment'}</button>{createProduct.isError&&<p className="error-text">{createProduct.error.message}</p>}</form></section>}
    <section className="panel"><div className="section-heading"><div><div className="eyebrow">REGISTERED TARGETS</div><h2>Company product environments</h2></div></div>{products.isLoading&&<p className="muted">Loading products…</p>}{products.isError&&<p className="error-text">Unable to load registered products.</p>}<div className="stack-list">{products.data?.map(product=><div className="list-card" key={product.id}><div><strong>{product.name}</strong><small>{product.environment} • {product.baseUrl} • {product.authType}</small></div><div className="button-row"><span className={`status ${product.active?'completed':'failed'}`}>{product.active?'ACTIVE':'INACTIVE'}</span>{canManageProducts&&<button className="secondary-btn" onClick={()=>setProductActive.mutate({id:product.id,value:!product.active})} disabled={setProductActive.isPending}>{product.active?'Deactivate':'Activate'}</button>}</div></div>)}</div>{setProductActive.isError&&<p className="error-text">{setProductActive.error.message}</p>}</section><CredentialProfilesSection products={products.data||[]} canManage={!!canManageProducts}/></main>}

  return <main className="page auth-page">
    <section className="hero-grid simple-hero">
      <div><div className="eyebrow">AI UAT ENGINEER • SECURE ACCESS</div><h1>{mode==='login'?'Welcome back':'Create your company workspace'}</h1><p className="lead">{mode==='login'?'Sign in once to continue with your registered products, requirements and UAT reports.':'Register the company once, create the first Company Admin, then invite the rest of the UAT team from inside the workspace.'}</p><div className="example-flow"><span>Company</span><i>→</i><span>UAT team</span><i>→</i><span>Product</span><i>→</i><span>Requirement</span><i>→</i><strong>Release decision</strong></div></div>
      <section className="panel"><div className="button-row"><button className={mode==='login'?'primary-btn':'secondary-btn'} type="button" onClick={()=>setMode('login')}>Existing account</button><button className={mode==='register'?'primary-btn':'secondary-btn'} type="button" onClick={()=>setMode('register')}>Create company</button></div>{mode==='login'&&<div className="stack-list"><div className="button-row">{googleEnabled?<a className="secondary-btn" href={ssoLoginUrl('google')}>Continue with Google</a>:<button className="secondary-btn" type="button" disabled title="Google SSO is not configured on this deployment">Google SSO — Not configured</button>}{githubEnabled?<a className="secondary-btn" href={ssoLoginUrl('github')}>Continue with GitHub</a>:<button className="secondary-btn" type="button" disabled title="GitHub SSO is not configured on this deployment">GitHub SSO — Not configured</button>}</div><p className="muted">{sso.isLoading?'Checking SSO availability…':'SSO signs in an existing registered or invited user by verified email. It never creates a company automatically.'}</p></div>}<form onSubmit={submit}>{mode==='register'&&<><label className="field"><span>Company name</span><input value={companyName} onChange={e=>setCompanyName(e.target.value)} required placeholder="Acme Technologies"/></label><label className="field"><span>Company slug <small>(optional)</small></span><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="acme-technologies"/></label></>}<label className="field"><span>Work email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" placeholder="you@company.com"/></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={12} autoComplete={mode==='login'?'current-password':'new-password'}/><small>Minimum 12 characters.</small></label><button className="primary-btn" disabled={login.isPending||register.isPending}>{login.isPending||register.isPending?'Please wait…':mode==='login'?'Sign in to workspace':'Create company workspace'}</button>{error&&<p className="error-text">{error.message}</p>}</form><p className="muted">{mode==='login'?'New company? Choose Create company above.':'Already registered? Choose Existing account above.'}</p></section>
    </section>

    <section className="panel"><div className="eyebrow">HOW A COMPANY STARTS</div><h2>From registration to the first autonomous UAT run</h2><p className="lead">You do not need to configure the whole platform on day one. Follow this guided company setup once, then future UAT runs become a simple product + requirement flow.</p><div className="use-case-grid">
      <article className="use-case-card"><strong>1. Register the company</strong><p>Enter company name, work email and password. The first account is created automatically as <b>Company Admin</b>.</p></article>
      <article className="use-case-card"><strong>2. Create the UAT team</strong><p>The Company Admin opens Account and adds <b>QA Manager</b>, <b>Tester</b> and <b>Viewer</b> users. Each user stays inside the same company tenant.</p></article>
      <article className="use-case-card"><strong>3. Register the product</strong><p>Add the product name, approved UAT/QA environment URL and authentication type once. Users no longer type target URLs for every run.</p></article>
      <article className="use-case-card"><strong>4. Configure secure access</strong><p>If the target requires login, attach a credential profile. Runtime secrets stay outside the UI and are resolved only during execution.</p></article>
      <article className="use-case-card"><strong>5. Upload the requirement</strong><p>Open Start UAT, select the registered product environment and upload the BRD, PRD, user story, PDF, DOCX or text requirement.</p></article>
      <article className="use-case-card"><strong>6. Start AI UAT Engineer</strong><p>The platform analyzes requirements, creates tests, generates automation, executes supported journeys, captures evidence and evaluates quality.</p></article>
      <article className="use-case-card"><strong>7. Review evidence</strong><p>QA and product users review PASS/FAIL results, traceability, diagnostics, evidence and performance signals from one workspace.</p></article>
      <article className="use-case-card"><strong>8. Make the release decision</strong><p>AI UAT Engineer returns an evidence-backed <b>READY</b> or <b>BLOCKED</b> recommendation so the team can focus on risk instead of report assembly.</p></article>
    </div><div className="example-flow"><span>Register</span><i>→</i><span>Add UAT users</span><i>→</i><span>Register product</span><i>→</i><span>Upload requirement</span><i>→</i><span>Autonomous UAT</span><i>→</i><strong>READY / BLOCKED</strong></div></section>

    <section className="panel"><div className="eyebrow">WHO DOES WHAT</div><h2>Simple roles for the company</h2><div className="role-grid"><article><strong>Company Admin</strong><p>Registers the company, adds users, manages products and controls the workspace.</p></article><article><strong>QA Manager</strong><p>Manages product environments and coordinates autonomous UAT execution.</p></article><article><strong>Tester</strong><p>Selects a registered product, uploads requirements and starts authorized UAT runs.</p></article><article><strong>Viewer</strong><p>Reviews results and evidence without execution permission.</p></article></div></section>
  </main>
}
