import { useQuery } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { auravisApi, downloadUrl } from '../api/auravis';

function statusClass(status:string){const s=status.toLowerCase();if(s==='completed'||s==='pass')return 'status completed';if(s==='failed'||s==='fail')return 'status failed';return 'status processing'}

export default function DashboardPage(){
  const [params,setParams]=useSearchParams();
  const stats=useQuery({queryKey:['pipeline-stats'],queryFn:auravisApi.stats,refetchInterval:10000});
  const runs=useQuery({queryKey:['pipeline-runs'],queryFn:auravisApi.runs,refetchInterval:10000});
  const aiRuntime=useQuery({queryKey:['ai-runtime'],queryFn:auravisApi.aiRuntime,refetchInterval:15000});
  const traffic=useQuery({queryKey:['traffic-stats'],queryFn:auravisApi.trafficStats,refetchInterval:15000});
  const recentVisits=useQuery({queryKey:['recent-visits'],queryFn:()=>auravisApi.recentVisits(20),refetchInterval:15000});
  const selectedId=params.get('run')||runs.data?.[0]?.id;
  const detail=useQuery({queryKey:['pipeline-run',selectedId],queryFn:()=>auravisApi.run(selectedId!),enabled:!!selectedId,refetchInterval:q=>q.state.data?.status==='RUNNING'||q.state.data?.status==='QUEUED'?2500:false});
  const data=stats.data;let result:any=null;try{result=detail.data?.resultJson?JSON.parse(detail.data.resultJson):null}catch{}
  const ai=aiRuntime.data;
  return <main className="page"><div className="eyebrow">AURAVIS 3.0 • LIVE MISSION CONTROL</div><h1>Mission Dashboard</h1><p className="lead">Requirement documents, mission results, Spring AI runtime state and privacy-friendly product traffic are restored from the backend after every page refresh.</p>
    <section className="panel"><div className="section-heading"><div><div className="eyebrow">M7 • SPRING AI INTELLIGENCE PLATFORM</div><h2>AI Runtime & 3.0 Progress</h2></div><span className={ai?.configured?'status completed':'status processing'}>{ai?.configured?'MODEL CONNECTED':'FALLBACK READY'}</span></div><p className="muted">Auravis 3.0 is moving the intelligence layer onto Spring AI while deterministic Java services continue to control execution, healing policy, persistence and release decisions.</p>{aiRuntime.isError&&<p className="error-text">Unable to read Spring AI runtime metadata.</p>}<div className="metric-grid four compact"><article><strong>{ai?.framework??'Spring AI'}</strong><span>AI Framework</span></article><article><strong>{ai?.springAiVersion??'—'}</strong><span>Spring AI Version</span></article><article><strong>{ai?.model??'—'}</strong><span>Configured Model</span></article><article><strong>{ai?.qaTools??'—'}</strong><span>Controlled QA Tools</span></article></div><div className="flow-grid"><div className="flow-step"><b>01</b><span>ChatClient runtime</span></div><div className="flow-step"><b>02</b><span>Controlled QA tool calling</span></div><div className="flow-step"><b>03</b><span>Spring AI RAG / pgvector</span></div><div className="flow-step"><b>04</b><span>Regression intelligence</span></div></div><p className="muted"><strong>Status:</strong> {ai?.m7Status??'IN_PROGRESS'} • {ai?.m7Focus??'Spring AI runtime, tools, RAG and regression intelligence'}</p></section>

    <section className="metric-grid"><article><strong>{data?.uploaded??'—'}</strong><span>Files Uploaded</span></article><article><strong>{data?.processed??'—'}</strong><span>Files Processed</span></article><article><strong>{data?.completed??'—'}</strong><span>Completed</span></article><article><strong>{data?.failed??'—'}</strong><span>Failed</span></article><article><strong>{data?.processing??'—'}</strong><span>Processing</span></article><article><strong>{data?`${data.completionRate}%`:'—'}</strong><span>Processing Rate</span></article></section>

    <section className="panel"><div className="section-heading"><div><div className="eyebrow">PRODUCT ANALYTICS</div><h2>Visitor & Traffic Trace</h2></div><span className="live">● Live</span></div><p className="muted">Anonymous route-level analytics only. Auravis does not persist raw visitor IP addresses.</p>{traffic.isError&&<p className="error-text">Unable to load visitor analytics.</p>}<div className="metric-grid four compact"><article><strong>{traffic.data?.uniqueVisitors??'—'}</strong><span>Unique Visitors</span></article><article><strong>{traffic.data?.uniqueVisitorsToday??'—'}</strong><span>Unique Today</span></article><article><strong>{traffic.data?.visitsToday??'—'}</strong><span>Page Views Today</span></article><article><strong>{traffic.data?.totalVisits??'—'}</strong><span>Total Page Views</span></article></div><div className="two-col analytics-split"><div><h3>Top Pages</h3>{traffic.data?.topPages?.length?<div className="stack-list">{traffic.data.topPages.map(page=><div className="list-card" key={page.path}><div><strong>{page.path}</strong><small>React route</small></div><span className="status completed">{page.visits} views</span></div>)}</div>:<p className="muted">No traffic recorded yet.</p>}</div><div><h3>Last 7 Days</h3>{traffic.data?.last7Days?.length?<div className="traffic-bars">{traffic.data.last7Days.map(day=>{const max=Math.max(...traffic.data!.last7Days.map(x=>x.visits),1);return <div className="traffic-row" key={day.date}><span>{day.label}</span><div className="traffic-track"><i style={{width:`${Math.max(3,day.visits*100/max)}%`}}/></div><b>{day.visits}</b></div>})}</div>:<p className="muted">No traffic recorded yet.</p>}<p className="muted">Most visited: <strong>{traffic.data?.mostVisitedPage??'—'}</strong></p></div></div>{recentVisits.data&&recentVisits.data.length>0&&<div className="table-wrap"><h3>Recent Anonymous Visits</h3><table><thead><tr><th>Time</th><th>Visitor</th><th>Page</th></tr></thead><tbody>{recentVisits.data.map((visit,index)=><tr key={`${visit.visitedAt}-${index}`}><td>{new Date(visit.visitedAt).toLocaleString()}</td><td>{visit.visitor}</td><td>{visit.path}</td></tr>)}</tbody></table></div>}</section>

    <section className="panel"><div className="section-heading"><div><div className="eyebrow">PERSISTED HISTORY</div><h2>Requirement Documents</h2></div><span className="live">● Live</span></div>{runs.isLoading&&<p className="muted">Loading requirement documents…</p>}{runs.isError&&<p className="error-text">Unable to load mission history from backend.</p>}{runs.data?.length===0&&<p className="muted">No uploaded requirement documents yet.</p>}{runs.data&&runs.data.length>0&&<div className="table-wrap"><table><thead><tr><th>Requirement File</th><th>Project</th><th>Status</th><th>Stage</th><th>Uploaded</th><th>Action</th></tr></thead><tbody>{runs.data.map(run=><tr key={run.id} className={run.id===selectedId?'selected-row':''}><td><strong>{run.fileName}</strong></td><td>{run.company||'default'}</td><td><span className={statusClass(run.status)}>{run.status}</span></td><td>{run.currentStage||'—'}</td><td>{run.createdAt?new Date(run.createdAt).toLocaleString():'—'}</td><td><button className="link-button" onClick={()=>setParams({run:run.id})}>View</button></td></tr>)}</tbody></table></div>}</section>
    {selectedId&&<section className="panel"><div className="section-heading"><div><div className="eyebrow">MISSION DETAIL</div><h2>{detail.data?.fileName||'Loading mission…'}</h2></div>{detail.data&&<span className={statusClass(detail.data.status)}>{detail.data.status}</span>}</div>{detail.isError&&<p className="error-text">Unable to load this mission.</p>}{detail.data&&<><p className="muted">{detail.data.company||'default'} • {detail.data.currentStage||'—'}</p>{detail.data.errorMessage&&<p className="error-text">{detail.data.errorMessage}</p>}{detail.data.status==='COMPLETED'&&<div className="form-actions"><a className="primary-btn" href={downloadUrl(detail.data.id,'xlsx')}>Download Excel</a><a className="secondary-btn" href={downloadUrl(detail.data.id,'json')}>Download JSON</a></div>}{result&&<><div className="metric-grid four compact"><article><strong>{result.requirements?.length??result.totalRequirements??'—'}</strong><span>Requirements</span></article><article><strong>{result.totalTests??result.testCases?.length??'—'}</strong><span>Generated Tests</span></article><article><strong>{(result.passedTests??0)+(result.failedTests??0)}</strong><span>Executed</span></article><article><strong>{result.qualityGate?.decision??result.decision??'—'}</strong><span>QA Decision</span></article></div><details className="result-json"><summary>View structured mission result</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}</>}</section>}
    <div className="page-actions"><Link className="primary-btn" to="/mission">Start New Mission</Link></div>
  </main>
}
