import { FormEvent, useState } from 'react';
import { auravisApi, LoadTestResult } from '../api/auravis';

export default function PerformancePage(){
  const [targetUrl,setTargetUrl]=useState('/actuator/health'); const [requests,setRequests]=useState(25); const [concurrency,setConcurrency]=useState(5);
  const [p95,setP95]=useState(1000); const [errorRate,setErrorRate]=useState(1); const [result,setResult]=useState<LoadTestResult>(); const [error,setError]=useState(''); const [running,setRunning]=useState(false);
  async function run(e:FormEvent){e.preventDefault();setRunning(true);setError('');try{setResult(await auravisApi.loadTest({targetUrl:targetUrl.startsWith('http')?targetUrl:`${window.location.origin}${targetUrl}`,requests,concurrency,maxP95Ms:p95,maxErrorRatePercent:errorRate}))}catch(x){setError(x instanceof Error?x.message:'Load test failed')}finally{setRunning(false)}}
  return <main className="page"><div className="eyebrow">PERFORMANCE</div><h1>Performance Gate</h1><p className="lead">Configure a safe load check, run it, then review one release decision.</p>
    <section className="panel"><div className="section-heading"><div><div className="eyebrow">STEP 1</div><h2>Configure</h2></div></div><form onSubmit={run}><div className="form-grid"><label className="field"><span>Target URL</span><input value={targetUrl} onChange={e=>setTargetUrl(e.target.value)}/><small>Use a non-destructive GET endpoint.</small></label><label className="field"><span>Requests</span><input type="number" min="1" max="500" value={requests} onChange={e=>setRequests(+e.target.value)}/></label><label className="field"><span>Concurrency</span><input type="number" min="1" max="25" value={concurrency} onChange={e=>setConcurrency(+e.target.value)}/></label><label className="field"><span>p95 limit (ms)</span><input type="number" min="1" value={p95} onChange={e=>setP95(+e.target.value)}/></label><label className="field"><span>Max error rate (%)</span><input type="number" min="0" max="100" step="0.1" value={errorRate} onChange={e=>setErrorRate(+e.target.value)}/></label></div><button className="primary-btn" disabled={running}>{running?'Running…':'Run performance gate'}</button></form>{error&&<p className="error-text">{error}</p>}</section>

    <section className="panel"><div className="section-heading"><div><div className="eyebrow">STEP 2</div><h2>Measured result</h2></div>{result&&<span className={`status ${result.sloPassed?'completed':'failed'}`}>{result.sloPassed?'PASS':'FAIL'}</span>}</div>{result?<div className="summary-strip"><article><strong>{result.p95Ms} ms</strong><span>p95</span></article><article><strong>{result.errorRatePercent.toFixed(2)}%</strong><span>Error rate</span></article><article><strong>{result.throughputPerSecond.toFixed(1)}/s</strong><span>Throughput</span></article><article><strong>{result.failures}</strong><span>Failures</span></article></div>:<p className="lead">Run the gate to see measured latency, throughput and failures.</p>}</section>

    <section className="panel"><div className="section-heading"><div><div className="eyebrow">STEP 3</div><h2>Release decision</h2></div>{result&&<span className={`status ${result.sloPassed?'completed':'failed'}`}>{result.releaseRisk} RISK</span>}</div>{result?<><h3>{result.sloPassed?'Performance gate passed':'Performance gate failed'}</h3><p className="lead">{result.summary}</p></>:<p className="lead">The release decision appears after the test completes.</p>}</section>
  </main>
}
