import { FormEvent, useState } from 'react';
import { auravisApi, LoadTestResult } from '../api/auravis';

export default function PerformancePage(){
 const [targetUrl,setTargetUrl]=useState('/actuator/health'); const [requests,setRequests]=useState(25); const [concurrency,setConcurrency]=useState(5);
 const [p95,setP95]=useState(1000); const [errorRate,setErrorRate]=useState(1); const [result,setResult]=useState<LoadTestResult>(); const [error,setError]=useState(''); const [running,setRunning]=useState(false);
 async function run(e:FormEvent){e.preventDefault();setRunning(true);setError('');try{setResult(await auravisApi.loadTest({targetUrl:targetUrl.startsWith('http')?targetUrl:`${window.location.origin}${targetUrl}`,requests,concurrency,maxP95Ms:p95,maxErrorRatePercent:errorRate}))}catch(x){setError(x instanceof Error?x.message:'Load test failed')}finally{setRunning(false)}}
 return <main className="page"><span className="eyebrow">M11 · PERFORMANCE & LOAD TESTING</span><h1>Performance quality gate</h1><p className="lead">Validate a safe GET journey under bounded load and turn latency, throughput and errors into a release decision.</p>
 <section className="panel"><form onSubmit={run}><div className="form-grid"><label className="field"><span>Target URL</span><input value={targetUrl} onChange={e=>setTargetUrl(e.target.value)}/><small>Use a non-destructive GET endpoint.</small></label><label className="field"><span>Total requests (max 500)</span><input type="number" min="1" max="500" value={requests} onChange={e=>setRequests(+e.target.value)}/></label><label className="field"><span>Concurrency (max 25)</span><input type="number" min="1" max="25" value={concurrency} onChange={e=>setConcurrency(+e.target.value)}/></label><label className="field"><span>p95 SLO (ms)</span><input type="number" min="1" value={p95} onChange={e=>setP95(+e.target.value)}/></label><label className="field"><span>Max error rate (%)</span><input type="number" min="0" max="100" step="0.1" value={errorRate} onChange={e=>setErrorRate(+e.target.value)}/></label></div><button className="primary-btn" disabled={running}>{running?'Running bounded load…':'Run performance gate'}</button></form>{error&&<p className="error-text">{error}</p>}</section>
 {result&&<><section className="summary-strip"><article><strong>{result.p50Ms} ms</strong><span>p50</span></article><article><strong>{result.p95Ms} ms</strong><span>p95</span></article><article><strong>{result.p99Ms} ms</strong><span>p99</span></article><article><strong>{result.throughputPerSecond.toFixed(1)}/s</strong><span>Throughput</span></article></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">RELEASE DECISION</span><h2>{result.sloPassed?'Performance gate passed':'Performance gate failed'}</h2></div><span className={`status ${result.sloPassed?'completed':'failed'}`}>{result.releaseRisk} RISK</span></div><p className="lead">{result.summary}</p><div className="example-flow"><span>{result.requests} requests</span><i>→</i><span>{result.concurrency} concurrent</span><i>→</i><span>{result.failures} failures ({result.errorRatePercent.toFixed(2)}%)</span><i>→</i><strong>{result.sloPassed?'RELEASE PERFORMANCE OK':'REVIEW BEFORE RELEASE'}</strong></div></section></>}
 </main>
}
