import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { aiUatApi } from '../api/aiUat';
import { platformApi } from '../api/platform';

export default function PlatformPage(){
 const session=useQuery({queryKey:['current-user'],queryFn:aiUatApi.currentUser,retry:false});
 const enabled=session.data?.role==='PLATFORM_ADMIN';
 const companies=useQuery({queryKey:['platform-companies'],queryFn:platformApi.companies,enabled});
 const products=useQuery({queryKey:['platform-products'],queryFn:platformApi.products,enabled});
 const users=useQuery({queryKey:['platform-users'],queryFn:platformApi.users,enabled});
 const operations=useQuery({queryKey:['platform-operations'],queryFn:platformApi.operations,enabled,refetchInterval:10000});
 const failures=useQuery({queryKey:['platform-failures'],queryFn:platformApi.failures,enabled,refetchInterval:10000});
 const [search,setSearch]=useState('');
 const [companyFilter,setCompanyFilter]=useState('ALL');
 const [statusFilter,setStatusFilter]=useState<'ALL'|'ACTIVE'|'INACTIVE'>('ALL');

 if(session.isLoading)return <main className="page"><p>Loading platform oversight…</p></main>;
 if(!enabled)return <main className="page"><div className="eyebrow">M20 • PLATFORM OVERSIGHT</div><h1>Platform owner access required</h1><p className="lead">This read-only console is restricted to PLATFORM_ADMIN.</p></main>;

 const companyRows=companies.data??[],productRows=products.data??[],userRows=users.data??[],operationRows=operations.data??[],failureRows=failures.data??[];
 const companyNameById=useMemo(()=>new Map(companyRows.map(c=>[c.id,c.name])),[companyRows]);
 const activeCompanies=companyRows.filter(x=>x.active).length,activeProducts=productRows.filter(x=>x.active).length,activeUsers=userRows.filter(x=>x.active).length;
 const authTypes=Array.from(new Set(productRows.map(p=>p.authType))).sort(),environments=Array.from(new Set(productRows.map(p=>p.environment))).sort(),roles=Array.from(new Set(userRows.map(u=>u.role))).sort();
 const norm=search.trim().toLowerCase();
 const matchesStatus=(active:boolean)=>statusFilter==='ALL'||(statusFilter==='ACTIVE'&&active)||(statusFilter==='INACTIVE'&&!active);
 const visibleCompanies=companyRows.filter(c=>matchesStatus(c.active)&&(!norm||`${c.name} ${c.slug}`.toLowerCase().includes(norm)));
 const visibleProducts=productRows.filter(p=>matchesStatus(p.active)&&(companyFilter==='ALL'||p.companyId===companyFilter)&&(!norm||`${p.name} ${p.environment} ${p.authType} ${companyNameById.get(p.companyId)??''}`.toLowerCase().includes(norm)));
 const visibleUsers=userRows.filter(u=>matchesStatus(u.active)&&(companyFilter==='ALL'||u.companyId===companyFilter)&&(!norm||`${u.email} ${u.role} ${companyNameById.get(u.companyId)??''}`.toLowerCase().includes(norm)));
 const visibleOperations=operationRows.filter(o=>(companyFilter==='ALL'||o.company===companyFilter)&&(!norm||`${o.fileName} ${o.status} ${o.currentStage} ${companyNameById.get(o.company)??o.company}`.toLowerCase().includes(norm)));
 const visibleFailures=failureRows.filter(f=>(companyFilter==='ALL'||f.company===companyFilter)&&(!norm||`${f.fileName} ${f.failedStage} ${f.diagnostic} ${companyNameById.get(f.company)??f.company}`.toLowerCase().includes(norm)));
 const companiesNeedingAttention=companyRows.filter(c=>!c.active||c.products===0||c.users===0);
 const running=operationRows.filter(o=>o.status==='RUNNING'||o.status==='QUEUED').length,completed=operationRows.filter(o=>o.status==='COMPLETED').length,failed=operationRows.filter(o=>o.status==='FAILED').length;
 const avgDuration=(()=>{const d=operationRows.map(o=>o.durationMillis).filter((x):x is number=>x!==null);return d.length?Math.round(d.reduce((a,b)=>a+b,0)/d.length/1000):0})();
 const fmtDuration=(ms:number|null)=>ms===null?'—':ms<1000?`${ms} ms`:`${Math.round(ms/1000)} s`;

 return <main className="page"><div className="eyebrow">4.0 • M20.1–M20.5</div><h1>Platform Owner Reporting</h1><p className="lead">Read-only cross-tenant oversight for adoption, access, UAT operations and failure diagnostics. Sensitive credentials and raw result payloads are not exposed.</p>
 <div className="summary-strip"><article><strong>{companyRows.length}</strong><span>Companies</span></article><article><strong>{activeProducts}/{productRows.length}</strong><span>Active product environments</span></article><article><strong>{activeUsers}/{userRows.length}</strong><span>Active users</span></article><article><strong>{companiesNeedingAttention.length}</strong><span>Companies needing attention</span></article></div>

 <section className="panel"><div className="section-heading"><div><div className="eyebrow">M20.4 • UAT OPERATIONS</div><h2>Cross-tenant UAT monitoring</h2></div><span className="status completed">AUTO REFRESH 10s</span></div><div className="metric-grid four compact"><article><strong>{running}</strong><span>Queued / running</span></article><article><strong>{completed}</strong><span>Completed</span></article><article><strong>{failed}</strong><span>Failed</span></article><article><strong>{avgDuration}s</strong><span>Average completed duration</span></article></div>{operations.isError?<p className="error-text">Unable to load UAT operations.</p>:<div className="table-wrap"><table><thead><tr><th>Company</th><th>Requirement</th><th>Status</th><th>Stage</th><th>Duration</th><th>Started</th></tr></thead><tbody>{visibleOperations.slice(0,50).map(o=><tr key={o.id}><td>{companyNameById.get(o.company)??o.company}</td><td><strong>{o.fileName}</strong></td><td><span className={`status ${o.status==='COMPLETED'?'completed':o.status==='FAILED'?'failed':''}`}>{o.status}</span></td><td>{o.currentStage}</td><td>{fmtDuration(o.durationMillis)}</td><td>{new Date(o.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}</section>

 <section className="panel"><div className="section-heading"><div><div className="eyebrow">M20.5 • FAILURES</div><h2>Failure diagnostics</h2></div><span>{visibleFailures.length} failures</span></div><p className="lead">Sanitized operational diagnostics help the platform owner identify where UAT stopped without exposing passwords, tokens, API keys or raw execution payloads.</p>{failures.isError?<p className="error-text">Unable to load failure reporting.</p>:visibleFailures.length===0?<p>No failed UAT runs recorded.</p>:<div className="table-wrap"><table><thead><tr><th>Company</th><th>Requirement</th><th>Failed stage</th><th>Diagnostic</th><th>Failed at</th></tr></thead><tbody>{visibleFailures.slice(0,50).map(f=><tr key={f.id}><td>{companyNameById.get(f.company)??f.company}</td><td><strong>{f.fileName}</strong></td><td>{f.failedStage}</td><td>{f.diagnostic}</td><td>{f.failedAt?new Date(f.failedAt).toLocaleString():'—'}</td></tr>)}</tbody></table></div>}</section>

 <section className="panel"><div className="section-heading"><div><div className="eyebrow">FILTERS</div><h2>Explore platform data</h2></div></div><div className="form-grid"><label className="field"><span>Search</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Company, product, email, requirement…"/></label><label className="field"><span>Company</span><select value={companyFilter} onChange={e=>setCompanyFilter(e.target.value)}><option value="ALL">All companies</option>{companyRows.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Status</span><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as 'ALL'|'ACTIVE'|'INACTIVE')}><option value="ALL">All</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label></div></section>

 <section className="panel"><div className="section-heading"><div><div className="eyebrow">PLATFORM HEALTH</div><h2>Adoption and access overview</h2></div><span className="status completed">READ ONLY</span></div><div className="metric-grid four compact"><article><strong>{activeCompanies}</strong><span>Active companies</span></article><article><strong>{environments.length}</strong><span>Environments in use</span></article><article><strong>{authTypes.length}</strong><span>Auth methods configured</span></article><article><strong>{roles.length}</strong><span>User roles in use</span></article></div></section>
 <section className="panel"><div className="section-heading"><div><div className="eyebrow">COMPANIES</div><h2>Company reporting</h2></div><span>{visibleCompanies.length} shown</span></div>{companies.isError?<p className="error-text">Unable to load companies.</p>:<div className="table-wrap"><table><thead><tr><th>Company</th><th>Status</th><th>Products</th><th>Users</th><th>Attention</th></tr></thead><tbody>{visibleCompanies.map(c=><tr key={c.id}><td><strong>{c.name}</strong><br/><small>{c.slug}</small></td><td><span className={`status ${c.active?'completed':'failed'}`}>{c.active?'ACTIVE':'INACTIVE'}</span></td><td>{c.products}</td><td>{c.users}</td><td>{!c.active?'Inactive company':c.products===0?'No products':c.users===0?'No users':'Healthy'}</td></tr>)}</tbody></table></div>}</section>
 <div className="two-col"><section className="panel"><div className="section-heading"><div><div className="eyebrow">PRODUCT FOOTPRINT</div><h2>Registered environments</h2></div><span>{visibleProducts.length} shown</span></div><div className="table-wrap"><table><thead><tr><th>Company</th><th>Product</th><th>Env</th><th>Auth</th><th>Status</th></tr></thead><tbody>{visibleProducts.map(p=><tr key={p.id}><td>{companyNameById.get(p.companyId)??'Unknown'}</td><td><strong>{p.name}</strong></td><td>{p.environment}</td><td>{p.authType}</td><td><span className={`status ${p.active?'completed':'failed'}`}>{p.active?'ACTIVE':'INACTIVE'}</span></td></tr>)}</tbody></table></div></section><section className="panel"><div className="section-heading"><div><div className="eyebrow">ACCESS FOOTPRINT</div><h2>Users and roles</h2></div><span>{visibleUsers.length} shown</span></div><div className="table-wrap"><table><thead><tr><th>Company</th><th>User</th><th>Role</th><th>Status</th></tr></thead><tbody>{visibleUsers.map(u=><tr key={u.id}><td>{companyNameById.get(u.companyId)??'Unknown'}</td><td>{u.email}</td><td>{u.role}</td><td><span className={`status ${u.active?'completed':'failed'}`}>{u.active?'ACTIVE':'INACTIVE'}</span></td></tr>)}</tbody></table></div></section></div>
 <section className="panel"><div className="section-heading"><div><div className="eyebrow">DISTRIBUTION</div><h2>Platform configuration mix</h2></div></div><div className="role-grid"><article><strong>Authentication methods</strong><p>{authTypes.length?authTypes.join(' • '):'No authentication methods yet.'}</p></article><article><strong>Environments</strong><p>{environments.length?environments.join(' • '):'No environments yet.'}</p></article><article><strong>User roles</strong><p>{roles.length?roles.join(' • '):'No user roles yet.'}</p></article><article><strong>Operational scope</strong><p>M20.5 adds sanitized failure reporting. Performance overview follows in M20.6.</p></article></div></section>
 </main>;
}
