import { Link } from 'react-router-dom';

const plans=[
 {name:'Daily Agent',price:'$50',period:'/ agent-day',badge:'PAY AS YOU GO',description:'Best for pilots, short UAT bursts, and teams that want to hire only the specialists needed for a mission.',features:['$50 per AI specialist per agent-day','Hire 1 to 100 agents in a day','No long-term commitment','Mission-scoped specialist selection'],cta:'Start with one agent'},
 {name:'Monthly Workforce',price:'$10,000',period:'/ month',badge:'TEAM PLAN',description:'A predictable pooled plan for delivery teams running AI-assisted UAT throughout the month.',features:['Includes 250 agent-days per month','Burst capacity up to 100 agents in a day','Effective included rate: $40 per agent-day','Additional usage: $45 per agent-day','Governed multi-agent orchestration'],cta:'Choose monthly'},
 {name:'Annual Workforce',price:'$100,000',period:'/ year',badge:'BEST VALUE',description:'For organizations standardizing governed AI UAT and release intelligence across products and release trains.',features:['Includes 3,000 agent-days per year','Burst capacity up to 100 agents in a day','Effective included rate: $33.33 per agent-day','Additional usage: $40 per agent-day','Save $20,000 vs 12 monthly subscriptions'],cta:'Choose annual'}
] as const;

export default function PricingPage(){
 return <main className="page"><section style={{textAlign:'center',maxWidth:920,margin:'0 auto 34px'}}><div className="eyebrow">AI UAT ENGINEER • PRICING</div><h1>Hire an AI UAT workforce when you need it</h1><p className="lead">Pricing is based on agent-days rather than unlimited compute. Start with one specialist for a day, or use pooled monthly and annual plans with burst access to the full 100-agent catalog.</p></section>
 <section className="roadmap-grid" style={{alignItems:'stretch'}}>{plans.map(plan=><article className="panel" key={plan.name} style={{display:'flex',flexDirection:'column',gap:14}}><div className="section-heading"><div><div className="eyebrow">{plan.badge}</div><h2 style={{marginBottom:4}}>{plan.name}</h2></div></div><div style={{display:'flex',alignItems:'baseline',gap:8,flexWrap:'wrap'}}><strong style={{fontSize:'clamp(2rem,5vw,3.4rem)',lineHeight:1}}>{plan.price}</strong><span className="muted">{plan.period}</span></div><p className="muted">{plan.description}</p><div style={{display:'grid',gap:10,margin:'4px 0 12px'}}>{plan.features.map(feature=><div key={feature} style={{display:'flex',gap:10,alignItems:'flex-start'}}><span aria-hidden="true">✓</span><span>{feature}</span></div>)}</div><div style={{marginTop:'auto'}}><Link className="primary-btn" style={{display:'inline-flex',width:'100%',justifyContent:'center',boxSizing:'border-box'}} to="/login">{plan.cta}</Link></div></article>)}</section>
 <section className="panel" style={{marginTop:28}}><div className="section-heading"><div><div className="eyebrow">HOW AGENT-DAYS WORK</div><h2>Flexible capacity without unlimited-compute risk</h2></div><span className="status processing">UP TO 100 / DAY</span></div><p className="lead">One agent-day means one AI specialist assigned to your UAT workforce for that day. Daily list price is $50, so a full 100-agent burst is $5,000/day. Monthly and annual plans discount committed usage while preserving the ability to burst up to 100 specialists when a release needs it.</p><div className="two-col"><article className="inner-card"><strong>Monthly economics</strong><p>250 included agent-days would cost $12,500 at daily list price. The $10,000 package gives a 20% committed-use discount.</p></article><article className="inner-card"><strong>Annual economics</strong><p>3,000 included agent-days would cost $150,000 at daily list price. The $100,000 annual package gives a 33% committed-use discount.</p></article></div><div className="button-row"><Link className="secondary-btn" to="/how-it-works">See how it works</Link><Link className="primary-btn" to="/login">Sign in</Link></div></section></main>;
}
