import { Link } from 'react-router-dom';

const plans=[
 {name:'Daily Agent',price:'$50',period:'/ agent / day',badge:'PAY AS YOU GO',description:'Hire only the AI specialists you need for a specific UAT mission.',features:['$50 per AI agent per day','Hire from 1 to 100 agents per day','Scale the workforce per mission','Ideal for pilots and burst testing'],cta:'Start with one agent'},
 {name:'Monthly Workforce',price:'$10,000',period:'/ month',badge:'TEAM PLAN',description:'A predictable monthly package for teams running AI-assisted UAT continuously.',features:['Continuous AI workforce access','Scale missions across the 100-agent catalog','Governed multi-agent orchestration','Best for active delivery teams'],cta:'Choose monthly'},
 {name:'Annual Workforce',price:'$100,000',period:'/ year',badge:'BEST VALUE',description:'Annual workforce package for organizations standardizing AI UAT across releases.',features:['Annual AI workforce package','Access to the 100-agent specialist catalog','Governance, evidence and release intelligence','Save $20,000 vs 12 monthly payments'],cta:'Choose annual'}
] as const;

export default function PricingPage(){
 return <main className="page"><section style={{textAlign:'center',maxWidth:900,margin:'0 auto 34px'}}><div className="eyebrow">AI UAT ENGINEER • PRICING</div><h1>Hire an AI UAT workforce when you need it</h1><p className="lead">Start with one specialist for a day or scale to a governed workforce of up to 100 AI agents. Choose daily, monthly, or annual access based on your delivery cadence.</p></section>
 <section className="roadmap-grid" style={{alignItems:'stretch'}}>{plans.map(plan=><article className="panel" key={plan.name} style={{display:'flex',flexDirection:'column',gap:14}}><div className="section-heading"><div><div className="eyebrow">{plan.badge}</div><h2 style={{marginBottom:4}}>{plan.name}</h2></div></div><div style={{display:'flex',alignItems:'baseline',gap:8,flexWrap:'wrap'}}><strong style={{fontSize:'clamp(2rem,5vw,3.4rem)',lineHeight:1}}>{plan.price}</strong><span className="muted">{plan.period}</span></div><p className="muted">{plan.description}</p><div style={{display:'grid',gap:10,margin:'4px 0 12px'}}>{plan.features.map(feature=><div key={feature} style={{display:'flex',gap:10,alignItems:'flex-start'}}><span aria-hidden="true">✓</span><span>{feature}</span></div>)}</div><div style={{marginTop:'auto'}}><Link className="primary-btn" style={{display:'inline-flex',width:'100%',justifyContent:'center',boxSizing:'border-box'}} to="/login">{plan.cta}</Link></div></article>)}</section>
 <section className="panel" style={{marginTop:28}}><div className="section-heading"><div><div className="eyebrow">WORKFORCE SCALE</div><h2>From one specialist to 100 agents</h2></div><span className="status processing">MAX 100 / DAY</span></div><p className="lead">Daily pricing scales linearly: one agent is $50/day and the maximum 100-agent daily workforce is $5,000/day. The orchestration layer still selects only the specialists needed for each mission rather than running all agents unnecessarily.</p><div className="button-row"><Link className="secondary-btn" to="/how-it-works">See how it works</Link><Link className="primary-btn" to="/login">Sign in</Link></div></section></main>;
}
