import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { aiUatApi, ssoLoginUrl } from '../api/aiUat';

const DEMO_EMAIL='demo.viewer@aiuat.example';
const DEMO_PASSWORD='DemoWalkthrough2026!';
const GoogleMark=()=> <span aria-hidden="true" style={{fontWeight:800,fontSize:24,fontFamily:'Arial,sans-serif'}}>G</span>;
const GitHubMark=()=> <span aria-hidden="true" style={{width:24,height:24,borderRadius:'50%',display:'inline-flex',alignItems:'center',justifyContent:'center',fontWeight:800,fontSize:12,border:'2px solid currentColor'}}>GH</span>;

export default function PublicLoginPage(){
 const qc=useQueryClient(); const navigate=useNavigate();
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [showRegistration,setShowRegistration]=useState(false); const [companyName,setCompanyName]=useState(''); const [slug,setSlug]=useState('');
 const sso=useQuery({queryKey:['sso-providers'],queryFn:aiUatApi.ssoProviders,retry:false});
 const login=useMutation({mutationFn:()=>aiUatApi.login(email,password),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['current-user']});navigate('/')}});
 const register=useMutation({mutationFn:async()=>{await aiUatApi.registerCompany({companyName,slug,adminEmail:email,password});return aiUatApi.login(email,password)},onSuccess:async()=>{await qc.invalidateQueries({queryKey:['current-user']});navigate('/')}});
 const submit=(e:FormEvent)=>{e.preventDefault();showRegistration?register.mutate():login.mutate()};
 const googleEnabled=sso.data?.providers.includes('google')??false; const githubEnabled=sso.data?.providers.includes('github')??false; const error=login.error||register.error;
 const provider:React.CSSProperties={display:'flex',alignItems:'center',justifyContent:'center',gap:12,width:'100%',minHeight:52,padding:'0 18px',borderRadius:12,fontSize:17,fontWeight:500,textDecoration:'none',background:'#fff',color:'#111',border:'1px solid #c8c8c8',boxSizing:'border-box'};
 return <main className="page auth-page"><section className="hero-grid"><div><div className="eyebrow">AI UAT ENGINEER • UAT DEMO</div><h1>Sign in and explore the product</h1><p className="lead">Turn requirements into evidence-backed UAT and a clear release decision.</p><div className="example-flow"><span>Requirement</span><i>→</i><span>AI + RAG</span><i>→</i><span>Automation</span><i>→</i><strong>READY / BLOCKED</strong></div><div className="button-row"><Link className="secondary-btn" to="/how-it-works">How It Works</Link></div></div>
 <section className="panel" style={{maxWidth:520}}><div className="eyebrow">SECURE ACCESS</div><h2>{showRegistration?'Create company workspace':'Welcome back'}</h2>
 {!showRegistration&&<div style={{display:'grid',gap:12,margin:'18px 0'}}><a href={googleEnabled?ssoLoginUrl('google'):undefined} aria-disabled={!googleEnabled} style={{...provider,opacity:googleEnabled?1:.5,cursor:googleEnabled?'pointer':'not-allowed'}}><GoogleMark/>Continue with Google</a><a href={githubEnabled?ssoLoginUrl('github'):undefined} aria-disabled={!githubEnabled} style={{...provider,opacity:githubEnabled?1:.5,cursor:githubEnabled?'pointer':'not-allowed'}}><GitHubMark/>Continue with GitHub</a></div>}
 {!showRegistration&&<div style={{display:'flex',alignItems:'center',gap:14,margin:'18px 0',color:'#6b7280'}}><span style={{height:1,background:'#e5e7eb',flex:1}}/><span>OR</span><span style={{height:1,background:'#e5e7eb',flex:1}}/></div>}
 <form onSubmit={submit}>{showRegistration&&<><label className="field"><span>Company name</span><input value={companyName} onChange={e=>setCompanyName(e.target.value)} required placeholder="Acme Technologies"/></label><label className="field"><span>Company slug <small>(optional)</small></span><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="acme-technologies"/></label></>}<label className="field"><span>{showRegistration?'Work email':'Email'}</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" placeholder="you@company.com"/></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={12} autoComplete={showRegistration?'new-password':'current-password'}/></label>{!showRegistration&&<div style={{display:'flex',justifyContent:'flex-end',margin:'-4px 0 12px'}}><Link to="/forgot-password">Forgot password?</Link></div>}<button className="primary-btn" style={{width:'100%',minHeight:50}} disabled={login.isPending||register.isPending}>{login.isPending||register.isPending?'Please wait…':showRegistration?'Create workspace':'Continue'}</button>{error&&<p className="error-text">{error.message}</p>}</form>
 <p className="muted" style={{marginTop:16}}>{showRegistration?'Already registered? ':'New company? '}<button type="button" className="link-button" onClick={()=>setShowRegistration(v=>!v)}>{showRegistration?'Sign in instead':'Create your workspace'}</button></p></section></section>
 <section className="panel"><div className="section-heading"><div><div className="eyebrow">DEMO WALKTHROUGH</div><h2>UAT visitor credential</h2></div><span className="status processing">UAT ONLY</span></div><p className="muted">Read-only demo access for visitors. Do not reuse these credentials elsewhere.</p><div className="two-col"><article className="inner-card"><strong>Email</strong><p>{DEMO_EMAIL}</p></article><article className="inner-card"><strong>Password</strong><p>{DEMO_PASSWORD}</p></article></div></section></main>;
}
