import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { aiUatApi } from '../api/aiUat';

export default function TestManagementPage(){
  const qc=useQueryClient();
  const [companyId,setCompanyId]=useState('');const [productId,setProductId]=useState('');
  const [requirementId,setRequirementId]=useState('REQ-001');const [testCondition,setTestCondition]=useState('Business user can complete the critical journey');const [testCaseId,setTestCaseId]=useState('TC-001');const [scriptId,setScriptId]=useState('');const [risk,setRisk]=useState('HIGH');const [expected,setExpected]=useState('Expected business outcome is observed');const [entry,setEntry]=useState(true);
  const [selectedId,setSelectedId]=useState('');const [executionId,setExecutionId]=useState('');const [status,setStatus]=useState('PASS');const [actual,setActual]=useState('Expected business outcome observed');const [defectRef,setDefectRef]=useState('');
  const records=useQuery({queryKey:['traceability',companyId,productId],queryFn:()=>aiUatApi.traceability(companyId,productId),enabled:!!companyId&&!!productId});
  const summary=useQuery({queryKey:['test-summary',companyId,productId],queryFn:()=>aiUatApi.testCompletionSummary(companyId,productId),enabled:!!companyId&&!!productId});
  const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['traceability',companyId,productId]}),qc.invalidateQueries({queryKey:['test-summary',companyId,productId]})])};
  const create=useMutation({mutationFn:()=>aiUatApi.createTraceability({companyId,productId,requirementId,testCondition,testCaseId,automationScriptId:scriptId||undefined,riskLevel:risk,expectedResult:expected,entryCriteriaMet:entry}),onSuccess:refresh});
  const record=useMutation({mutationFn:()=>aiUatApi.recordTraceabilityExecution(selectedId,{executionId,status,actualResult:actual,defectRef:defectRef||undefined}),onSuccess:refresh});
  const submit=(e:FormEvent)=>{e.preventDefault();create.mutate()};const submitExecution=(e:FormEvent)=>{e.preventDefault();record.mutate()};
  const s=summary.data;
  return <main className="page"><div className="eyebrow">M13 • ISTQB-ALIGNED TEST MANAGEMENT</div><h1>Test Management & Traceability</h1><p className="lead">Connect requirement → test condition → test case → approved automation → execution → evidence/defect → test completion recommendation.</p>
    <section className="panel"><div className="form-grid"><label className="field"><span>Company ID</span><input value={companyId} onChange={e=>setCompanyId(e.target.value)} placeholder="Company UUID"/></label><label className="field"><span>Product ID</span><input value={productId} onChange={e=>setProductId(e.target.value)} placeholder="Product UUID"/></label></div></section>
    {s&&<section className="summary-strip"><article><strong>{s.total}</strong><span>Total tests</span></article><article><strong>{s.passed}</strong><span>Passed</span></article><article><strong>{s.failed}</strong><span>Failed</span></article><article><strong>{s.automationCoveragePercent.toFixed(0)}%</strong><span>Automation linkage</span></article></section>}
    {s&&<section className="panel"><div className="section-heading"><div><div className="eyebrow">TEST COMPLETION</div><h2>{s.exitCriteriaMet?'Exit criteria met':'Exit criteria not met'}</h2></div><span className={`status ${s.exitCriteriaMet?'completed':'failed'}`}>{s.releaseRecommendation}</span></div><p className="muted">High-risk tests: {s.highRisk} • failed high-risk: {s.failedHighRisk} • not run: {s.notRun}</p></section>}
    <section className="panel"><div className="eyebrow">PLAN & TRACE</div><h2>Create test traceability</h2><form onSubmit={submit}><div className="form-grid"><label className="field"><span>Requirement ID</span><input value={requirementId} onChange={e=>setRequirementId(e.target.value)}/></label><label className="field"><span>Test Case ID</span><input value={testCaseId} onChange={e=>setTestCaseId(e.target.value)}/></label><label className="field"><span>Risk</span><select value={risk} onChange={e=>setRisk(e.target.value)}><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label className="field"><span>Approved Automation Script ID</span><input value={scriptId} onChange={e=>setScriptId(e.target.value)} placeholder="Optional UUID"/></label></div><label className="field"><span>Test condition</span><textarea rows={3} value={testCondition} onChange={e=>setTestCondition(e.target.value)}/></label><label className="field"><span>Expected result</span><textarea rows={3} value={expected} onChange={e=>setExpected(e.target.value)}/></label><label className="field"><span><input type="checkbox" checked={entry} onChange={e=>setEntry(e.target.checked)}/> Entry criteria met</span></label><button className="primary-btn" disabled={!companyId||!productId||create.isPending}>Create traceability</button>{create.isError&&<p className="error-text">{create.error.message}</p>}</form></section>
    <section className="panel"><div className="eyebrow">EXECUTION RESULT</div><h2>Record expected vs actual</h2><form onSubmit={submitExecution}><div className="form-grid"><label className="field"><span>Traceability record</span><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select test</option>{records.data?.map(r=><option key={r.id} value={r.id}>{r.testCaseId} • {r.requirementId}</option>)}</select></label><label className="field"><span>Execution ID</span><input value={executionId} onChange={e=>setExecutionId(e.target.value)} placeholder="RUN-123"/></label><label className="field"><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option>PASS</option><option>FAIL</option><option>BLOCKED</option></select></label><label className="field"><span>Defect reference</span><input value={defectRef} onChange={e=>setDefectRef(e.target.value)} placeholder="Required when FAIL"/></label></div><label className="field"><span>Actual result</span><textarea rows={3} value={actual} onChange={e=>setActual(e.target.value)}/></label><button className="primary-btn" disabled={!selectedId||!executionId||record.isPending}>Record execution</button>{record.isError&&<p className="error-text">{record.error.message}</p>}</form></section>
    <section className="panel"><div className="section-heading"><div><div className="eyebrow">TRACEABILITY MATRIX</div><h2>Requirement coverage</h2></div></div><div className="table-wrap"><table><thead><tr><th>Requirement</th><th>Test Case</th><th>Risk</th><th>Automation</th><th>Status</th><th>Defect</th><th>Exit</th></tr></thead><tbody>{records.data?.map(r=><tr key={r.id}><td>{r.requirementId}</td><td>{r.testCaseId}</td><td>{r.riskLevel}</td><td>{r.automationScriptId?'Linked':'Manual'}</td><td><span className={`status ${r.status==='PASS'?'completed':r.status==='NOT_RUN'?'processing':'failed'}`}>{r.status}</span></td><td>{r.defectRef||'—'}</td><td>{r.exitCriteriaMet?'✓':'—'}</td></tr>)}{records.data?.length===0&&<tr><td colSpan={7} className="muted">No traceability records yet.</td></tr>}</tbody></table></div></section>
  </main>
}
