const API_BASE=import.meta.env.VITE_API_BASE_URL||'';
async function get<T>(path:string):Promise<T>{const r=await fetch(`${API_BASE}${path}`,{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error(`API ${r.status}: ${path}`);return r.json()}
export type PlatformCompany={id:string;name:string;slug:string;active:boolean;products:number;users:number};
export type PlatformProduct={id:string;companyId:string;name:string;environment:string;authType:string;active:boolean};
export type PlatformUser={id:string;companyId:string;email:string;role:string;active:boolean};
export type PlatformOperation={id:string;company:string;fileName:string;status:string;currentStage:string;createdAt:string;completedAt:string|null;durationMillis:number|null;failureSummary:string|null};
export type PlatformOperationDetail=PlatformOperation&{diagnostic:string|null;resultAvailable:boolean;evidenceAvailable:boolean;releaseDecision:string|null};
export type PlatformFailure={id:string;company:string;fileName:string;failedStage:string;createdAt:string;failedAt:string|null;diagnostic:string};
export type PlatformPerformance={pipelineRuns:number;averagePipelineDurationMs:number;maxPipelineDurationMs:number;loadTestRuns:number;loadTestSloPassed:number;averageLoadP95Ms:number;averageThroughputPerSecond:number;averageLoadErrorRatePercent:number};
export type PlatformAuditEvent={eventType:string;scopeId:string;subject:string;detail:string;occurredAt:string};
export type PlatformDiagnostics={health:string;uptimeMs:number;memory:{usedMb:number;remainingMb:number;maxMb:number;usedPercent:number};uatRuns:{total:number;running:number;failed:number;failedLast24h:number};traffic:{totalVisits:number;uniqueVisitors:number;visitsLast24h:number;uniqueVisitorsLast24h:number};tenants:{companies:number;users:number;products:number;activeProducts:number};generatedAt:string};
export type PlatformTrafficStats={totalVisits:number;visitsToday:number;uniqueVisitors:number;uniqueVisitorsToday:number;authenticatedVisitorsToday:number;activeAuthenticatedUsers:number;mostVisitedPage:string;last7Days:{date:string;label:string;visits:number}[];topPages:{path:string;visits:number}[]};
export type PlatformRecentVisit={path:string;identity:string;visitor:string;companyId:string|null;visitedAt:string};
export type PlatformDbTable={name:string;rows:number;visibleColumns:number};
export type PlatformDbPage={table:string;columns:string[];rows:Record<string,unknown>[];page:number;size:number;totalRows:number;totalPages:number};
export const platformApi={companies:()=>get<PlatformCompany[]>('/api/platform/companies'),products:()=>get<PlatformProduct[]>('/api/platform/products'),users:()=>get<PlatformUser[]>('/api/platform/users'),operations:()=>get<PlatformOperation[]>('/api/platform/operations'),operation:(id:string)=>get<PlatformOperationDetail>(`/api/platform/operations/${id}`),failures:()=>get<PlatformFailure[]>('/api/platform/failures'),performance:()=>get<PlatformPerformance>('/api/platform/performance'),audit:()=>get<PlatformAuditEvent[]>('/api/platform/audit'),diagnostics:()=>get<PlatformDiagnostics>('/api/platform/diagnostics'),traffic:()=>get<PlatformTrafficStats>('/api/analytics/stats'),recentVisits:(limit=50)=>get<PlatformRecentVisit[]>(`/api/analytics/recent?limit=${limit}`),databaseTables:()=>get<PlatformDbTable[]>('/api/platform/database/tables'),databaseRows:(table:string,page=0,size=20)=>get<PlatformDbPage>(`/api/platform/database/tables/${encodeURIComponent(table)}?page=${page}&size=${size}`)};
